WebProject/Controllers/GezilecekyerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SehrimiTani.BusinessLayer;
using SehrimiTani.Entities;

namespace WebProject.Controllers
{
    public class GezilecekyerController : Controller
    {
        private GezilecekYerlerManager gezilecekYerlerManager = new GezilecekYerlerManager();
        // GET: Gezilecekyer
        public ActionResult Index()
        {
            return View(gezilecekYerlerManager.List());
        }

        // GET: Gezilecekyer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gezilecekyer gezilecekyer = gezilecekYerlerManager.Find(x=>x.Id==id.Value);
            if (gezilecekyer == null)
            {
                return HttpNotFound();
            }
            return View(gezilecekyer);
        }

        // GET: Gezilecekyer/Create
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Gezilecekyer gezilecekyer)
        {
            ModelState.Remove("CreatedOn");
            ModelState.Remove("ModifiedOn");
            ModelState.Remove("ModifiedUsername");
            if (ModelState.IsValid)
            {
                gezilecekYerlerManager.Insert(gezilecekyer);
                return RedirectToAction("Index");
            }

            return View(gezilecekyer);
        }

        // GET: Gezilecekyer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gezilecekyer gezilecekyer = gezilecekYerlerManager.Find(x => x.Id == id.Value);
            if (gezilecekyer == null)
            {
                return HttpNotFound();
            }
            return View(gezilecekyer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Gezilecekyer gezilecekyer)
        {
            ModelState.Remove("CreatedOn");
            ModelState.Remove("ModifiedOn");
            ModelState.Remove("ModiiedUsername");
            if (ModelState.IsValid)
            {
                Gezilecekyer gez = gezilecekYerlerManager.Find(x => x.Id == gezilecekyer.Id);
                gez.Icerik = gezilecekyer.Icerik;
                gez.Resim = gezilecekyer.Resim;
                gez.Baslik = gezilecekyer.Baslik;
                gezilecekYerlerManager.Update(gez);
                return RedirectToAction("Index");
            }
            return View(gezilecekyer);
        }

        // GET: Gezilecekyer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gezilecekyer gezilecekyer = gezilecekYerlerManager.Find(x => x.Id == id.Value);
            if (gezilecekyer == null)
            {
                return HttpNotFound();
            }
            return View(gezilecekyer);
        }

        // POST: Gezilecekyer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gezilecekyer gezilecekyer = gezilecekYerlerManager.Find(x => x.Id == id);
            gezilecekYerlerManager.Delete(gezilecekyer);
            return RedirectToAction("Index");
        }
    }
}

WebProject/Views/Gezilecekyer/Create.cshtml
@model SehrimiTani.Entities.Gezilecekyer

@{
    ViewBag.Title = "Create";
}
<link href="~/css/validation-summary.css" rel="stylesheet" />

<div class="row"style="margin-left:350px;margin-top:150px;">
    <div class="col-md-8 col-md-offset-2">
        <h2>Create</h2>
        <hr />
    </div>
   
</div> 
<div class="row" style="margin-left:350px;">
    <div class="col-md-4 col-md-offset-2">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Gezilecekyer</h4>
                <hr />
                @Html.ValidationSummary(false)
                <div class="form-group">
                    @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Resim, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3 col-lg-3" style="">
                        <img src="~/images/Harput-Kalesi.jpg" class="img-circle" width="128" height="128"style="margin-bottom:10px" />
                        
                        <input type="file" name="ProfileImage" id="ProfileImage" class="form-control" style="width:300px" /><br />
                        <span class="glyphicon glyphicon-info-sign">&nbsp;</span>
                        <span><i>Lütfen jpg, jpeg ya da png formatı kullanın.</i></span>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus">Ekle</span>
                        </button>
                        @Html.ActionLink("Back to List", "Index","Gezilecekyer",null,new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        }

       

    </div>
</div>
<script>

    function hideSlider() {
        var element = document.getElementById('Silider');
        var menu = document.getElementById("ftco-navbar");

        element.hidden = true;
    };
    window.onload = hideSlider();
</script>

WebProject/Views/Gezilecekyer/Delete.cshtml
@model SehrimiTani.Entities.Gezilecekyer

@{
    Layout = null;
}
<div class="row" style="margin-left:350px;margin-top:150px;">
    <div class="col-md-8 col-md-offset-1">
        <h2>Delete</h2>
        <h3>Bunu silmek istediğinizden emin misiniz?</h3>
        <hr />
    </div>

</div>

<div class="row" style="font-size:18px; margin-left:350px; ">
    <div class="col-md-11 col-md-offset-1" style="margin-right:0px">
        <div class="row">
            <h4>Gezilecekyer</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Baslik)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Baslik)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Resim)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Resim)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Icerik)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Icerik)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CreatedOn)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreatedOn)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ModifiedOn)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ModifiedOn)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ModifiedUsername)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ModifiedUsername)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-actions no-color">

                <input type="submit" value="Delete" class="btn btn-dark" /> |
             
                @Html.ActionLink("Back to List", "Index", "Gezilecekyer", null, new { @class = "btn btn-dark" })

            </div>
            }
        </div>
    </div>
    </div>

<script>

    function hideSlider() {
        var element = document.getElementById('Silider');
        var menu = document.getElementById("ftco-navbar");
        var foter = document.getElementById("ftco-footer");



        element.hidden = true;
        menu.hidden = true;
        foter.hidden = true;
    };
    window.onload = hideSlider();
</script>

WebProject/Views/Gezilecekyer/Details.cshtml
@model SehrimiTani.Entities.Gezilecekyer

@{
    Layout = null;
}
<div class="row" style="margin-left:350px;margin-top:150px;">
    <div class="col-md-8 col-md-offset-2">

        <h2>Details</h2>
        <hr />
    </div>

</div>
<div class="row" style="margin-left:350px;">
    <div class="col-md-4 col-md-offset-2">

        <div>
            <h4>Gezilecekyer</h4>
            @Html.ValidationSummary(false)
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Baslik)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Baslik)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Resim)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Resim)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Icerik)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Icerik)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CreatedOn)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreatedOn)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ModifiedOn)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ModifiedOn)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ModifiedUsername)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ModifiedUsername)
                </dd>

            </dl>
        </div>
        <p>

            @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
            @Html.ActionLink("Back to List", "Index", "Gezilecekyer", null, new { @class = "btn btn-primary" })


        </p>

    </div>
    </div>

WebProject/Views/Gezilecekyer/Edit.cshtml
@model SehrimiTani.Entities.Gezilecekyer

@{
    Layout = null;
}


<link href="~/css/validation-summary.css" rel="stylesheet" />
<link href="~/scss/style.scss" rel="stylesheet" />
<div class="row" style="margin-left:350px;margin-top:150px;">
    <div class="col-md-8 col-md-offset-2">
        <h2>Edit</h2>
        <hr />
    </div>

</div>
<div class="row" style="margin-left:350px;">
    <div class="col-md-12 col-md-offset-2">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Gezilecekyer</h4>
            <hr />
            @Html.ValidationSummary(false)
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Resim, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3 col-lg-3" style="">
                    <img src="~/images/Harput-Kalesi.jpg" class="img-circle" width="128" height="128" style="margin-bottom:10px" />

                    <input type="file" name="ProfileImage" id="ProfileImage" class="form-control" style="width:300px" /><br />
                    <span class="glyphicon glyphicon-info-sign">&nbsp;</span>
                    <span><i>Lütfen jpg, jpeg ya da png formatı kullanın.</i></span>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ModifiedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModifiedOn, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ModifiedUsername, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModifiedUsername, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
        }

      
    </div>
</div>
<script>

    function hideSlider() {
        var element = document.getElementById('Silider');
        var menu = document.getElementById("ftco-navbar");

        element.hidden = true;
    };
    window.onload = hideSlider();
</script>

WebProject/Views/Gezilecekyer/Index.cshtml
@model IEnumerable<SehrimiTani.Entities.Gezilecekyer>

@{
    ViewBag.Title = "Index";
}


<div class="row" style="margin-left:350px;margin-top:150px;">
    <div class="col-md-8 col-md-offset-1">
        <h2>Gezilecek Yer Listesi</h2>
        <hr />
    </div>

</div>
<div class="">
    <div class="col-md-11 col-md-offset-1" style="margin-right:0px">
        <p>
           
            <a href="/Gezilecekyer/Create" class="btn btn-outline-dark">
                <span class="glyphicon glyphicon-plus"></span>Create
            </a>
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Baslik)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Resim)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Icerik)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedUsername)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Baslik)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Resim)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Icerik)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedUsername)
                    </td>
                    <td>
                        <a href="/Gezilecekyer/Edit/@item.Id" class="btn btn-outline-dark">
                            <span class="glyphicon glyphicon-edit"></span>Edit
                        </a>
                        <a href="/Gezilecekyer/Details/@item.Id" class="btn btn-outline-dark"style="padding-top:5px;">
                            <span class="glyphicon glyphicon-search"></span>Details
                        </a>
                        <a href="/Gezilecekyer/Delete/@item.Id" class="btn btn-outline-dark" style="padding-top:5px;">
                            <span class="glyphicon glyphicon-trash"></span>Delete
                        </a>
                       
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

<script>

    function hideSlider() {
        var element = document.getElementById('Silider');
        var menu = document.getElementById("ftco-navbar");

        element.hidden = true;
    };
    window.onload = hideSlider();
</script>